# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://horizontalhuman.github.io
baseurl:          /

author:
  name:           'horizontalhuman'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/horizontalhuman/horizontalhuman.github.io
